service_account_email: playable@fair-solution-173518.iam.gserviceaccount.com
credentials_file: service_account.json
project_id: fair-solution-173518
machine_type: n1-standard-1
image: debian-7
instance_list:
  - web-server-1,web-server-2
  - db-server
  - lb-server

db_name: employee_db
db_user: db_user
db_user_password: Passw0rd
ansible_user: mmumshad
ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
