- name: Set up networking
  hosts: localhost
  gather_facts: False
  vars:
    region: us-central1
    members: us-central1-a/web-server-1,us-central1-a/web-server-2
  tasks:
    - name: Allow HTTP traffic
      gce_net:
        fwname: all-http
        name: default
        allowed: tcp:80
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"

    - name: Allow HTTP traffic
      gce_net:
        fwname: all-database
        name: default
        allowed: tcp:3306
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"

    - name: Create the load-balancer and add members
      gce_lb:
        name: lb1
        region: "{{ region }}"
        members: "{{ members }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"